import Header from '@/components/header'
import './globals.css'
import { Sora } from 'next/font/google'
import ParticlesContainer from '@/components/particles-container'
import Navigation from '@/components/navigation'

const sora = Sora({ 
  subsets: ['latin'] ,
  variable: '--font-sora',
  weight : ['100', '200', '300', '400', '500', '600', '700', '800']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sora.className} overflow-hidden leading-relaxed font-sora`}>
        <div className='w-full h-screen bg-gradient-to-br from-[#43115C] from-5% via-via-mixer via-25% to-[#0A010F] to-90%
           opacity-90 -z-[50]
         '>
          <ParticlesContainer />
          <Header />
          <Navigation />
          {children}
          </div>
        </body>
    </html>
  )
}
